### PR TITLE
Support map types and others

### PR DESCRIPTION
**Pull request by mpapierski**
This PR includes missing variants for the ledger integration and does some necessary housekeeping.

- Add a generator for missing variants
  - Map
  - ByteArray (32-byte is used as it's most common)
  - Tuple1
  - Any (used a simple struct that implements `CLTyped` and presents itself `CLType::Any` variant)
- Update the code to 1.5.4 tag and version the lock file
- Bump toolchain to be aligned with the node

### CODE REVIEW

**Comment by ftheirs** [comment]
Hi @mpapierski, will this be merged soon? Can we use this branch to generate the testvectors for the Ledger app?

**Comment by neithanmo** [comment]
@mpapierski i noticed that you want support for:
- maps
- byte array 32-bytes,
- tuple1
- Any

we are adding support for this in the ledger application, however, we are defining an invariant for that, for example, one of our invariants is that map fields must not be any container type, just plain types. otherwise, we would be hit for stackoverflow issues due to recursion while parsing nested types, for example: 
`map<u32, map<map<map<key, map>>>>` and so on. 
the tuple1 type is currently supported.

That being said I noticed that regarding MAPS, your proposed changes are including container types as map fields.

**Comment by mpapierski** [comment]
Hello @neithanmo 

> @mpapierski i noticed that you want support for:
> 
>     * maps
> 
>     * byte array 32-bytes,
> 
>     * tuple1
> 
>     * Any
> 
> 

The main objective of this PR was to add support for missing Map type, then as part of cleaning I realized there are other missing CLType variants, so I added other variants for the generator as an extra.

> we are adding support for this in the ledger application, however, we are defining an invariant for that, for example, one of our invariants is that map fields must not be any container type, just plain types. otherwise, we would be hit for stackoverflow issues due to recursion while parsing nested types, for example: `map<u32, map<map<map<key, map>>>>` and so on. the tuple1 type is currently supported.

We do have a fix for this case and perhaps it is something that can be borrowed into the ledger app - we do recursive deserialization with a hard limit for a call depth limit of 50 here: https://github.com/casper-network/casper-node/blob/787bb89691f7e9b1dcc86f813bbd0edbdc1356a1/types/src/cl_type.rs#L24-L25. If the recursion depth is exceeded we return `ExceededRecursionDepth` error. That should be consistent with the node. 

> 
> That being said I noticed that regarding MAPS, your proposed changes are including container types as map fields.

That's correct - `CLType::Map` has a `K` and `V` types.

**Review by hoffmannjan — APPROVED** [review]
LGTM

**Pull request merged**
